### ISSUE TITLE
Question: Can it be that it has problem if non-standard directories

### ISSUE THREAD

**Issue by tomasnorre** [shipmonk-rnd/composer-dependency-analyser#149]
Hi, 

I'm the maintainer of the TYPO3 Crawler, which used non-standard vendor-dir. 
Everything is in a `.Build` directory. 

When running the tool. I get 

```shell
PHP Warning:  foreach() argument must be of type array|object, null given in /home/tomas/Projects/Private/crawler/.Build/vendor/shipmonk/composer-dependency-analyser/src/Analyser.php on line 410
```

Which indicates from code, that no class loading is found https://github.com/shipmonk-rnd/composer-dependency-analyser/blob/master/src/Analyser.php#L410

My composer.json looks like this for the autload part.

```json
"autoload": {
        "psr-4": {
            "AOE\\Crawler\\": "Classes"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "AOE\\Crawler\\Tests\\": "Tests",
            "TYPO3\\CMS\\Core\\Tests\\": ".Build/vendor/typo3/cms-core/Tests"
        }
    },
```

Can it be that this tool have problems with projects with non-standard directory structure?

**Comment by janedbal** [comment]
That PHP Warning is definitelly a bug when no composer autoloader is found (fixed in #150).

--------

But since you have regular composer autoload sections, it should not happen (composer autoloader should be present). Few questions to verify the state:
1. How did you install this tool and how do you run it?
2. Did you setup [custom vendor dir](https://getcomposer.org/doc/06-config.md#vendor-dir) in your composer.json?
3. Does this tool output `No composer class loader detected!` (to stderr) ?

**Comment by janedbal** [comment]
I assume you are mentioning [this repository](https://github.com/tomasnorre/crawler), right? 

Looks like you are using custom classloader instead of composer's one, which currently is not supported. I'll try to add support, but I'm currently getting some class not found failures, so I need to check even that.

```
```

**Comment by janedbal** [comment]
Can you test #151? With that, I was able to make the tool work over your repository, but I'm not certain if autoloading is working correctly there. I'll check that more deeply tomorrow.

**Comment by janedbal** [comment]
The main **problem is that the autoloader the package uses (`ClassAliasLoader`) is broken** and is unable to load classes referenced in the codebase (failing on Fatal Error).


------


You can exclude paths that references those broken symbols to make it work, but it will definitelly affect the results:

```php

use ShipMonk\ComposerDependencyAnalyser\Config\Configuration;

$config = new Configuration();

return $config->addPathsToExclude([
    __DIR__ . '/.Build/vendor/typo3/cms-core/Tests',
    __DIR__ . '/Tests/Acceptance',
]);
```

Another idea is to enable composer's classloader for the analysis (which seems to work):

```php
use ShipMonk\ComposerDependencyAnalyser\Config\Configuration;

/** @var \Composer\Autoload\ClassLoader $classLoader */
$classLoader = require __DIR__ . '/.Build/vendor/autoload.php';
$classLoader->register();

return new Configuration();
```

**Comment by tomasnorre** [comment]
Thanks for all you information. Will try to set it up according to your advice.

**Comment by janedbal** [comment]
Closing as stale.
