### ISSUE TITLE
reports PHP_IBAN\IBAN as Unknown classes

### ISSUE THREAD

**Issue by gemal** [shipmonk-rnd/composer-dependency-analyser#50]
I'm using https://github.com/globalcitizen/php-iban in my project

but when running `composer-dependency-analyser` `PHP_IBAN\IBAN` is being reported as a `Unknown classes`

in my code I have:
`use PHP_IBAN\IBAN;`

and everything else looks Ok I think:
https://github.com/globalcitizen/php-iban/blob/master/oophp-iban.php

is this a bug in `composer-dependency-analyser` or on my side?

**Comment by janedbal** [comment]
Composer-dependency-analyser is [relying of composer's classmap](https://github.com/shipmonk-rnd/composer-dependency-analyser?tab=readme-ov-file#usage) which does not contain those classes because the library is not using [autoloader](https://www.php.net/manual/en/language.oop5.autoload.php) for its classes. See its [composer.json](https://github.com/globalcitizen/php-iban/blob/ed8f5c0/composer.json#L9) - because it uses `files` section (and not `psr-x` or `classmap`), composer uses [require](https://www.php.net/manual/en/function.require.php) for those, see snippet of [its docs](https://getcomposer.org/doc/04-schema.md#files):

> If you want to require certain files explicitly on every request then you can use the files autoloading mechanism. This is useful if your package includes PHP functions that cannot be autoloaded by PHP.

This `files` section should be used for functions (which lack autoloading mechanism), not classes.

-----

In order to deal with libraries like this one, we would need to scan all those `files` sections of all `composer.json` dependencies and detect if some classes are present there.

**Comment by janedbal** [comment]
> btw globalcitizen/php-iban is also listed in Found unused dependencies
so perhaps there is a link between those 2 errors?

Yes, since all classes from that library are not present on composer's classmap (thus we cannot detect to which package such class belongs), it sees such package as unused.

**Comment by janedbal** [comment]
:thinking: Maybe we could try autoloading such class in that case and use its reflection to detect the package. 

We generally try to avoid autoloading (which is one the things giving this tool so imense performance), but this should not cause significant slowdown.

**Comment by janedbal** [comment]
This is fixed in master (by #51). But I want to verify few more things before releasing it, you can use `dev-master` in the meantime (or ignore the error in the meantime).

Thank you for this report!

**Comment by janedbal** [comment]
Version `1.2.0` no longer suffers this issue.
